### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by CaptainProductions** [SharkFinProductions/TiniGameEngine#3]
What about Safari? :P

**Comment by SharkFinPro** [comment]
What?

**Comment by SharkFinPro** [comment]
Its supported...
http://www.w3schools.com/graphics/canvas_intro.asp

**Comment by SharkFinPro** [comment]
Read The ReadMe

**Comment by XtremePlayzCODE** [comment]
WebKit is supported, and Safari is WebKit.
