### ISSUE TITLE
Shark, you have created a monster

### ISSUE THREAD

**Issue by XtremePlayzCODE** [SharkFinProductions/TiniGameEngine#5]
You went too far in the file `test.html`. I mean look at it!

**Comment by SharkFinPro** [comment]
heh heh - testing everything

**Comment by SharkFinPro** [comment]
BTW - Im releasing an update soon, but im having troubles because my wifi keeps dropping.

**Comment by SharkFinPro** [comment]
Released - please do not update this without asking me first. i have alot of updates that im making rn.
Make it in a fork please.
